# Generated by Django 2.0.2 on 2018-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('contato_funcao', models.CharField(max_length=20, verbose_name='Função do Contato')),
                ('contato_nome', models.CharField(max_length=40, verbose_name='Nome do Contato')),
                ('incr_estadual', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('cgc_cpf', models.CharField(max_length=18, verbose_name='cgc/cpf')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereço')),
                ('cidade', models.CharField(max_length=40, verbose_name='cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='uf')),
                ('cep', models.CharField(max_length=9, verbose_name='cep')),
                ('telefone1', models.CharField(max_length=20, verbose_name='telefone1')),
                ('telefone2', models.CharField(max_length=20, verbose_name='telefone2')),
                ('telefone3', models.CharField(max_length=20, verbose_name='telefone3')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('obs', models.TextField(blank=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
