# Generated by Django 2.0.2 on 2018-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180309_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='cep'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cgc_cpf',
            field=models.CharField(blank=True, max_length=18, verbose_name='cgc/cpf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=40, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_funcao',
            field=models.CharField(blank=True, max_length=20, verbose_name='Função do Contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, verbose_name='uf'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='incr_estadual',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone3',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone3'),
        ),
    ]
